name: Python Continuous Integration

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
   schedule:
    - cron: '42 20 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python Virt Env
        run: python -m venv venv
      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pipx install -r requirements.txt; fi
          sudo pip3 install pyxel
      - name: Lint with ruff
        run: |
          source venv/bin/activate
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Do commands
        run: |
          source venv/bin/activate
          cd project
      - name: Test with unittest
        run: |
          source venv/bin/activate
          python -m unittest discover
